name: fluxer_dart
version: 1.2.0
description: Dart SDK for Fluxer a free and open source instant messaging and VoIP platform.
homepage: https://fluxer.app
repository: https://github.com/fluxerapp/dart_sdk


environment:
  sdk: '>=2.18.0 <4.0.0'

dependencies:
  dio: '^5.7.0'
  one_of: '>=1.5.0 <2.0.0'
  one_of_serializer: '>=1.5.0 <2.0.0'
  built_value: '>=8.4.0 <9.0.0'
  built_collection: '>=5.1.1 <6.0.0'

dev_dependencies:
  built_value_generator: '>=8.4.0 <9.0.0'
  build_runner: any
  test: '^1.16.0'
